const reservedWords = new Map();
const reservedSymbols = new Map();
reservedSymbols.set("+", "OPSOMA");
reservedSymbols.set("-", "OPSUB");
reservedSymbols.set("*", "OPMUL");
reservedSymbols.set("div", "OPDIV");
reservedSymbols.set("(", "AP");
reservedSymbols.set(")", "FP");
reservedSymbols.set(";", "PONTOVIRG");
reservedSymbols.set(":", "DOISPONTOS");
reservedSymbols.set("<", "MENOR");        
reservedSymbols.set("<>", "DIFERENTE");        
reservedSymbols.set("=", "IGUAL");
reservedSymbols.set(">", "MAIOR");
reservedSymbols.set("<=", "MENORIGUAL");
reservedSymbols.set(">=", "MAIORIGUAL");
reservedSymbols.set(":=", "ATRIBUICAO");
reservedSymbols.set(",", "VIRG");
reservedSymbols.set(".", "PONTO");
reservedWords.set("begin", "BEGIN");
reservedWords.set("end", "END");
reservedWords.set("then", "THEN");
reservedWords.set("else", "ELSE");
reservedWords.set("if", "IF");
reservedWords.set("while", "WHILE");
reservedWords.set("do", "DO");
reservedWords.set("program", "PROGRAM");
reservedWords.set("procedure", "PROCEDURE");
reservedWords.set("int", "INT");
reservedWords.set("boolean", "BOOLEAN");
reservedWords.set("read", "READ");
reservedWords.set("write", "WRITE");
reservedWords.set("true", "TRUE");
reservedWords.set("false", "FALSE");
reservedWords.set("and", "AND");
reservedWords.set("or", "OR");
reservedWords.set("var", "VAR");

export {reservedWords, reservedSymbols};